// src/data/dummyData.js

const dummyData = [
  {
    id: 1,
    name: "김민호",
    birthDate: "1995-06-15",
    age: 28,
    gender: "Male",
    admissionDate: "2020-01-15",
    dorm: "생활관1",
    healthInsurance: "Yes",
    disability: "No",
    mentalScore: 75,
  },
  {
    id: 2,
    name: "이지수",
    birthDate: "1992-11-30",
    age: 31,
    gender: "Female",
    admissionDate: "2019-07-20",
    dorm: "생활관2",
    healthInsurance: "Yes",
    disability: "No",
    mentalScore: 85,
  },
  {
    id: 3,
    name: "박진영",
    birthDate: "1990-03-10",
    age: 34,
    gender: "Male",
    admissionDate: "2021-05-17",
    dorm: "생활관3",
    healthInsurance: "No",
    disability: "Yes",
    mentalScore: 65,
  },
  {
    id: 4,
    name: "최민아",
    birthDate: "1998-08-25",
    age: 25,
    gender: "Female",
    admissionDate: "2022-03-12",
    dorm: "생활관4",
    healthInsurance: "Yes",
    disability: "No",
    mentalScore: 95,
  },
  {
    id: 5,
    name: "정현우",
    birthDate: "1988-01-05",
    age: 36,
    gender: "Male",
    admissionDate: "2018-11-20",
    dorm: "생활관1",
    healthInsurance: "Yes",
    disability: "No",
    mentalScore: 70,
  },
  {
    id: 6,
    name: "윤소희",
    birthDate: "1996-07-12",
    age: 27,
    gender: "Female",
    admissionDate: "2020-08-01",
    dorm: "생활관2",
    healthInsurance: "No",
    disability: "Yes",
    mentalScore: 90,
  },
  {
    id: 7,
    name: "한지훈",
    birthDate: "1994-02-17",
    age: 30,
    gender: "Male",
    admissionDate: "2021-04-15",
    dorm: "생활관3",
    healthInsurance: "Yes",
    disability: "No",
    mentalScore: 60,
  },
  {
    id: 8,
    name: "서유나",
    birthDate: "1991-12-01",
    age: 32,
    gender: "Female",
    admissionDate: "2019-12-10",
    dorm: "생활관4",
    healthInsurance: "Yes",
    disability: "No",
    mentalScore: 80,
  },
  {
    id: 9,
    name: "강동민",
    birthDate: "1993-09-09",
    age: 30,
    gender: "Male",
    admissionDate: "2021-06-25",
    dorm: "생활관1",
    healthInsurance: "No",
    disability: "Yes",
    mentalScore: 55,
  },
  {
    id: 10,
    name: "임혜진",
    birthDate: "1995-04-14",
    age: 29,
    gender: "Female",
    admissionDate: "2022-02-18",
    dorm: "생활관2",
    healthInsurance: "Yes",
    disability: "No",
    mentalScore: 88,
  },
];

export default dummyData;
