const toDoListData = [
  // 긍정적사고 - 김민호, 윤소희
  {
    id: 1,
    content: "오늘 있었던 좋은 일 3가지 적기",
    keywordName: "긍정적사고",
    users: ["김민호", "윤소희"],
  },
  {
    id: 2,
    content: "긍정적인 명언 찾아 읽기",
    keywordName: "긍정적사고",
    users: ["김민호", "윤소희"],
  },
  {
    id: 3,
    content: "어떤 것이든 목표 세우기",
    keywordName: "긍정적사고",
    users: ["김민호", "윤소희"],
  },
  {
    id: 4,
    content: "하루 동안 부정적인 말 안하기",
    keywordName: "긍정적사고",
    users: ["김민호", "윤소희"],
  },
  {
    id: 5,
    content: "스트레스 해소 방법 연구하기",
    keywordName: "긍정적사고",
    users: ["김민호", "윤소희"],
  },
  {
    id: 6,
    content: "신나는 음악 듣기",
    keywordName: "긍정적사고",
    users: ["김민호", "윤소희"],
  },
  {
    id: 7,
    content: "명상 15분 하기",
    keywordName: "긍정적사고",
    users: ["김민호", "윤소희"],
  },
  {
    id: 8,
    content: "자신의 강점 찾기",
    keywordName: "긍정적사고",
    users: ["김민호", "윤소희"],
  },
  {
    id: 9,
    content: "오늘 뿌듯했던 일 기록하기",
    keywordName: "긍정적사고",
    users: ["김민호", "윤소희"],
  },
  {
    id: 10,
    content: "자신의 단점을 인정하고 장점으로 바꿔보기",
    keywordName: "긍정적사고",
    users: ["김민호", "윤소희"],
  },
  {
    id: 11,
    content: "주변 사람에게 감사 인사 전하기",
    keywordName: "긍정적사고",
    users: ["김민호", "윤소희"],
  },
  {
    id: 12,
    content: "다른 사람에게 먼저 인사하기",
    keywordName: "긍정적사고",
    users: ["김민호", "윤소희"],
  },
  {
    id: 13,
    content: "주변 사람 칭찬하기",
    keywordName: "긍정적사고",
    users: ["김민호", "윤소희"],
  },
  {
    id: 14,
    content: "거울 보고 웃어보기",
    keywordName: "긍정적사고",
    users: ["김민호", "윤소희"],
  },
  {
    id: 15,
    content: "취미 찾아보기",
    keywordName: "긍정적사고",
    users: ["김민호", "윤소희"],
  },
  // 공동체 - 이지수, 한지훈
  {
    id: 16,
    content: "주변 사람에게 인사하기",
    keywordName: "공동체",
    users: ["이지수", "한지훈"],
  },
  {
    id: 17,
    content: "센터에서 제공하는 식사에 참여하기",
    keywordName: "공동체",
    users: ["이지수", "한지훈"],
  },
  {
    id: 18,
    content: "센터에서 제공하는 프로그램에 참여하기",
    keywordName: "공동체",
    users: ["이지수", "한지훈"],
  },
  {
    id: 19,
    content: "센터 내부 정리 및 청소 하기",
    keywordName: "공동체",
    users: ["이지수", "한지훈"],
  },
  {
    id: 20,
    content: "새로운 사람과 대화 시도하기",
    keywordName: "공동체",
    users: ["이지수", "한지훈"],
  },
  {
    id: 21,
    content: "그룹 활동에 참여해보기 (예: 게임, 대화)",
    keywordName: "공동체",
    users: ["이지수", "한지훈"],
  },
  {
    id: 22,
    content: "다른 사람의 이야기를 들어주기",
    keywordName: "공동체",
    users: ["이지수", "한지훈"],
  },
  {
    id: 23,
    content: "다른 사람과 함께 산책하기",
    keywordName: "공동체",
    users: ["이지수", "한지훈"],
  },
  {
    id: 24,
    content: "취미나 관심사를 공유하기",
    keywordName: "공동체",
    users: ["이지수", "한지훈"],
  },
  {
    id: 25,
    content: "주변 사람에게 인사하기",
    keywordName: "공동체",
    users: ["이지수", "한지훈"],
  },
  {
    id: 26,
    content: "센터 내 직원 분들에게 감사 인사 하기",
    keywordName: "공동체",
    users: ["이지수", "한지훈"],
  },
  {
    id: 27,
    content: "센터에서 제공하는 프로그램에 참여하기",
    keywordName: "공동체",
    users: ["이지수", "한지훈"],
  },
  {
    id: 28,
    content: "같은 취미를 가지고 있는 사람 찾기",
    keywordName: "공동체",
    users: ["이지수", "한지훈"],
  },
  {
    id: 29,
    content: "센터에서 제공하는 식사에 참여하기",
    keywordName: "공동체",
    users: ["이지수", "한지훈"],
  },
  {
    id: 30,
    content: "다른 사람과 함께 산책하기",
    keywordName: "공동체",
    users: ["이지수", "한지훈"],
  },
  // 자기계발 - 박진영, 서유나
  {
    id: 31,
    content: "오늘의 감사한 일 3가지 적기",
    keywordName: "자기계발",
    users: ["박진영", "서유나"],
  },
  {
    id: 32,
    content: "10분간 명상하기",
    keywordName: "자기계발",
    users: ["박진영", "서유나"],
  },
  {
    id: 33,
    content: "하루 계획 세우기",
    keywordName: "자기계발",
    users: ["박진영", "서유나"],
  },
  {
    id: 34,
    content: "좋아하는 책 한 챕터 읽기",
    keywordName: "자기계발",
    users: ["박진영", "서유나"],
  },
  {
    id: 35,
    content: "아침 일찍 일어나기",
    keywordName: "자기계발",
    users: ["박진영", "서유나"],
  },
  {
    id: 36,
    content: "새로운 취미 찾기",
    keywordName: "자기계발",
    users: ["박진영", "서유나"],
  },
  {
    id: 37,
    content: "자신의 강점 3가지 적어보기",
    keywordName: "자기계발",
    users: ["박진영", "서유나"],
  },
  {
    id: 38,
    content: "관심 있는 주제로 30분 공부하기",
    keywordName: "자기계발",
    users: ["박진영", "서유나"],
  },
  {
    id: 39,
    content: "봉사 활동 찾아보기(온라인/오프라인)",
    keywordName: "자기계발",
    users: ["박진영", "서유나"],
  },
  {
    id: 40,
    content: "이전에 작성한 감사한 일 다시 읽어보기",
    keywordName: "자기계발",
    users: ["박진영", "서유나"],
  },
  {
    id: 41,
    content: "간단한 예산 계획 세우기",
    keywordName: "자기계발",
    users: ["박진영", "서유나"],
  },
  {
    id: 42,
    content: "스트레스 관리법 한 가지 배우기",
    keywordName: "자기계발",
    users: ["박진영", "서유나"],
  },
  {
    id: 43,
    content: "하루 일과 반성하기(일기 쓰기)",
    keywordName: "자기계발",
    users: ["박진영", "서유나"],
  },
  {
    id: 44,
    content: "15분간 스트레칭 하기",
    keywordName: "자기계발",
    users: ["박진영", "서유나"],
  },
  {
    id: 45,
    content: "친구나 가족에게 감사 메시지 보내기",
    keywordName: "자기계발",
    users: ["박진영", "서유나"],
  },
  // 운동 - 최민아, 강동민
  {
    id: 46,
    content: "가벼운 스트레칭 5분 하기",
    keywordName: "운동",
    users: ["최민아", "강동민"],
  },
  {
    id: 47,
    content: "산책 10분 하기",
    keywordName: "운동",
    users: ["최민아", "강동민"],
  },
  {
    id: 48,
    content: "의자에 앉았다 일어나기 10회 하기",
    keywordName: "운동",
    users: ["최민아", "강동민"],
  },
  {
    id: 49,
    content: "어깨 돌리기 10회 하기",
    keywordName: "운동",
    users: ["최민아", "강동민"],
  },
  {
    id: 50,
    content: "손목과 발목 돌리기 5분 하기",
    keywordName: "운동",
    users: ["최민아", "강동민"],
  },
  {
    id: 51,
    content: "산책 10분 하기",
    keywordName: "운동",
    users: ["최민아", "강동민"],
  },
  {
    id: 52,
    content: "목 스트레칭 5분 하기",
    keywordName: "운동",
    users: ["최민아", "강동민"],
  },
  {
    id: 53,
    content: "의자에 앉아서 다리 들어 올리기 10회 하기",
    keywordName: "운동",
    users: ["최민아", "강동민"],
  },
  {
    id: 54,
    content: "스쿼트 5회 하기",
    keywordName: "운동",
    users: ["최민아", "강동민"],
  },
  {
    id: 55,
    content: "팔 양쪽으로 뻗어서 원을 그리며 돌리기 1분 하기",
    keywordName: "운동",
    users: ["최민아", "강동민"],
  },
  {
    id: 56,
    content: "팔 양쪽으로 뻗어서 원을 그리며 돌리기 1분 하기",
    keywordName: "운동",
    users: ["최민아", "강동민"],
  },
  {
    id: 57,
    content: "손목 스트레칭 5분 하기",
    keywordName: "운동",
    users: ["최민아", "강동민"],
  },
  {
    id: 58,
    content: "앞 뒤로 손뼉 치기 5분 하기",
    keywordName: "운동",
    users: ["최민아", "강동민"],
  },
  {
    id: 59,
    content: "제자리 걷기 5분 하기",
    keywordName: "운동",
    users: ["최민아", "강동민"],
  },
  {
    id: 60,
    content: "스쿼트 10회 하기",
    keywordName: "운동",
    users: ["최민아", "강동민"],
  },
  // 건강관리 - 정현우, 임혜진
  {
    id: 61,
    content: "아침 스트레칭 10분",
    keywordName: "건강관리",
    users: ["정현우", "임혜진"],
  },
  {
    id: 62,
    content: "물 8잔 마시기 목표 설정",
    keywordName: "건강관리",
    users: ["정현우", "임혜진"],
  },
  {
    id: 63,
    content: "일어나자마자 물 한 잔 마시기",
    keywordName: "건강관리",
    users: ["정현우", "임혜진"],
  },
  {
    id: 64,
    content: "근처 병원 위치 찾아보기",
    keywordName: "건강관리",
    users: ["정현우", "임혜진"],
  },
  {
    id: 65,
    content: "하루 세 끼 먹기",
    keywordName: "건강관리",
    users: ["정현우", "임혜진"],
  },
  {
    id: 66,
    content: "비타민 복용하기",
    keywordName: "건강관리",
    users: ["정현우", "임혜진"],
  },
  {
    id: 67,
    content: "무료 건강 검진 예약",
    keywordName: "건강관리",
    users: ["정현우", "임혜진"],
  },
  {
    id: 68,
    content: "7시간 이상 잠자기",
    keywordName: "건강관리",
    users: ["정현우", "임혜진"],
  },
  {
    id: 69,
    content: "과일 1개 이상 먹기",
    keywordName: "건강관리",
    users: ["정현우", "임혜진"],
  },
  {
    id: 70,
    content: "12시 전에 잠자기",
    keywordName: "건강관리",
    users: ["정현우", "임혜진"],
  },
  {
    id: 71,
    content: "비타민 복용하기",
    keywordName: "건강관리",
    users: ["정현우", "임혜진"],
  },
  {
    id: 72,
    content: "아침 산책 15분",
    keywordName: "건강관리",
    users: ["정현우", "임혜진"],
  },
  {
    id: 73,
    content: "야채가 포함된 식사하기",
    keywordName: "건강관리",
    users: ["정현우", "임혜진"],
  },
  {
    id: 74,
    content: "가벼운 산책 20분 하기",
    keywordName: "건강관리",
    users: ["정현우", "임혜진"],
  },
  {
    id: 75,
    content: "물 10잔 마시기",
    keywordName: "건강관리",
    users: ["정현우", "임혜진"],
  },
];

export default toDoListData;
