const users = [
  {
    userId: 1,
    email: "김민호@example.com",
    name: "김민호",
    birthDate: "1995-06-15",
    age: 28,
    gender: "남자",
    admissionDate: "2020-01-15",
    dorm: "생활관1",
    healthInsurance: "Yes",
    disability: "No",
    mentalScore: 75,
  },
  {
    userId: 2,
    email: "이지수@example.com",
    name: "이지수",
    birthDate: "1992-11-30",
    age: 31,
    gender: "여자",
    admissionDate: "2019-07-20",
    dorm: "생활관2",
    healthInsurance: "Yes",
    disability: "No",
    mentalScore: 85,
  },
  {
    userId: 3,
    email: "박진영@example.com",
    name: "박진영",
    birthDate: "1990-03-10",
    age: 34,
    gender: "남자",
    admissionDate: "2021-05-17",
    dorm: "생활관3",
    healthInsurance: "No",
    disability: "Yes",
    mentalScore: 65,
  },
  {
    userId: 4,
    email: "최민아@example.com",
    name: "최민아",
    birthDate: "1998-08-25",
    age: 25,
    gender: "여자",
    admissionDate: "2022-03-12",
    dorm: "생활관4",
    healthInsurance: "Yes",
    disability: "No",
    mentalScore: 95,
  },
  {
    userId: 5,
    email: "정현우@example.com",
    name: "정현우",
    birthDate: "1988-01-05",
    age: 36,
    gender: "남자",
    admissionDate: "2018-11-20",
    dorm: "생활관1",
    healthInsurance: "Yes",
    disability: "No",
    mentalScore: 70,
  },
  {
    userId: 6,
    email: "윤소희@example.com",
    name: "윤소희",
    birthDate: "1996-07-12",
    age: 27,
    gender: "여자",
    admissionDate: "2020-08-01",
    dorm: "생활관2",
    healthInsurance: "No",
    disability: "Yes",
    mentalScore: 90,
  },
  {
    userId: 7,
    email: "한지훈@example.com",
    name: "한지훈",
    birthDate: "1994-02-17",
    age: 30,
    gender: "남자",
    admissionDate: "2021-04-15",
    dorm: "생활관3",
    healthInsurance: "Yes",
    disability: "No",
    mentalScore: 60,
  },
  {
    userId: 8,
    email: "서유나@example.com",
    name: "서유나",
    birthDate: "1991-12-01",
    age: 32,
    gender: "여자",
    admissionDate: "2019-12-10",
    dorm: "생활관4",
    healthInsurance: "Yes",
    disability: "No",
    mentalScore: 80,
  },
  {
    userId: 9,
    email: "강동민@example.com",
    name: "강동민",
    birthDate: "1993-09-09",
    age: 30,
    gender: "남자",
    admissionDate: "2021-06-25",
    dorm: "생활관1",
    healthInsurance: "No",
    disability: "Yes",
    mentalScore: 55,
  },
  {
    userId: 10,
    email: "임혜진@example.com",
    name: "임혜진",
    birthDate: "1995-04-14",
    age: 29,
    gender: "여자",
    admissionDate: "2022-02-18",
    dorm: "생활관2",
    healthInsurance: "Yes",
    disability: "No",
    mentalScore: 88,
  },
];

export default users;
